# Base configs
baseurl: "https://kundan-ugale.github.io/photography"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Photography by Kundan Ugale"
subtitle: "See the realistic world through my eyes!"
author: "Kundan Ugale"
header:
 title: "Photography"
 subtitle: "by Kundan Ugale"
footer:
 name: "Hey there, my name is Kundan"
 bio: "I am a developer and a tech aficionado from India. Love making teeny tiny apps solving tiny problems in life and now learning photography."
 github: ""
web_design: "AJ"
social_urls:
  facebook: "#"
  twitter: "#"
  instagram: "#"
  dribbble: "#"
  linkedin: "#"
  github: "#"
